version: '2'

services:
    fhem:
        expose:
            - "8083"
            - "7072"
        ports:
            - "8083:8083"
            - "7072:7072"
        build: fhem
        privileged: true
        devices:
          - "/dev/ttyUSB0:/dev/ttyUSB0"
        volumes:
            - ./fhem/start.sh:/opt/fhem/start.sh
            - ./fhem/log/:/opt/fhem/log
            - ./fhem/backup/:/opt/fhem/backup
            - ./fhem/data/fhem.cfg:/opt/fhem/fhem.cfg
            - ./fhem/data/FHEM/controls.txt:/opt/fhem/FHEM/controls.txt
            - ./fhem/data/FHEM/99_myUtils.pm:/opt/fhem/FHEM/99_myUtils.pm
            - ./fhem/data/contrib/dblog/db.conf:/opt/fhem/contrib/dblog/db.conf
        networks:
            - code-network
        depends_on:
            - "mysql"

    homebridge:
        expose:
            - "51826"
            - "8282"
            - "5353"
        ports:
            - "51826:51826"
            - "8282:8282"
            - "5353:5353"
        build: homebridge
        volumes:
            - ./homebridge/start.sh:/root/start.sh
            - ./homebridge/config.json:/root/.homebridge/config.json
        networks:
            - code-network
        depends_on:
            - "fhem"

    mysql:
        expose:
            - "3306"
            - "33060"
        ports:
            - "3306:3306"
            - "33060:33060"
        image: mysql/mysql-server:5.7
        volumes:
            - ./mysql/init.sql:/docker-entrypoint-initdb.d/fhem-init.sql
            - ./mysql/data:/var/lib/mysql
        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
        networks:
            - code-network

networks:
    code-network:
        driver: bridge